import type { SelectorSet } from "../shared/types";

export const STABLE_ATTRS = ["data-testid", "data-qa", "data-cy", "data-test", "name", "aria-label"];

const FRAMEWORK_ATTR_PREFIXES = ["data-react", "data-v-", "data-svelte-", "data-ng-", "data-debug", "data-server-rendered"];

function isFrameworkAttr(name: string): boolean {
  return FRAMEWORK_ATTR_PREFIXES.some((p) => name.startsWith(p));
}

// Detect IDs that are auto-generated by frameworks and not stable across sessions.
export function isGeneratedId(id: string): boolean {
  if (!id) return true;
  if (/^ember\d+$/.test(id)) return true;
  // LinkedIn (and other Ember apps) embed ember IDs into compound ids like
  // `overlay-conversation-card-ember51` — the suffix changes every session.
  if (/[-_]ember\d+$/.test(id)) return true;
  if (/^react-[a-zA-Z0-9]+$/.test(id)) return true;
  if (id.startsWith("__")) return true;
  // Pure alphanumeric ≥8 chars with both letters and digits = UUID/hash-like
  if (id.length >= 8 && /^[a-zA-Z0-9]+$/.test(id) && /[0-9]/.test(id) && /[a-zA-Z]/.test(id)) return true;
  return false;
}

function getStableAttribute(el: HTMLElement): [string, string] | null {
  if (el.id && !isGeneratedId(el.id)) return ["id", el.id];
  for (const attr of STABLE_ATTRS) {
    const val = el.getAttribute(attr);
    if (val) return [attr, val];
  }
  const role = el.getAttribute("role");
  if (role) return ["role", role];
  return null;
}

function escapeCssValue(val: string): string {
  return CSS.escape(val);
}

const DYNAMIC_CLASS_TOKENS = new Set([
  "active",
  "selected",
  "disabled",
  "enabled",
  "focused",
  "focus",
  "hover",
  "open",
  "closed",
  "current",
]);

function isStableClassToken(token: string): boolean {
  const value = String(token || "").trim().toLowerCase();
  if (!value) return false;
  if (value.length < 3 || value.length > 80) return false;
  if (!/[a-z]/.test(value)) return false;
  if (DYNAMIC_CLASS_TOKENS.has(value)) return false;
  if (/^ember\d+$/.test(value)) return false;
  if (/(^|[-_])ember\d+$/.test(value)) return false;
  if (/^react-[a-z0-9]+$/.test(value)) return false;
  if (/^(css|sc)-[a-z0-9]{5,}$/.test(value)) return false;
  if (/^jsx-\d+$/.test(value)) return false;
  // Reject hash-like tokens with long unbroken suffixes.
  if (/^[a-z]+[0-9]{5,}$/.test(value)) return false;
  if (/^[a-z0-9]{14,}$/.test(value) && !value.includes("-") && !value.includes("_")) return false;
  return true;
}

function scoreClassToken(token: string): number {
  let score = Math.min(token.length, 24);
  if (token.includes("__")) score += 25; // BEM block__element
  if (token.includes("--")) score += 10; // BEM modifier
  if (token.includes("-")) score += 6;
  if (/[0-9]/.test(token)) score -= 4;
  return score;
}

function getStableClassTokens(el: HTMLElement): string[] {
  const tokens = Array.from(el.classList).filter(isStableClassToken);
  tokens.sort((a, b) => scoreClassToken(b) - scoreClassToken(a));
  return tokens.slice(0, 4);
}

function querySelectorCount(selector: string): number {
  try {
    return document.querySelectorAll(selector).length;
  } catch {
    return Number.MAX_SAFE_INTEGER;
  }
}

function withTypeQualifier(el: HTMLElement, selector: string): string | null {
  if (!(el instanceof HTMLButtonElement) && !(el instanceof HTMLInputElement)) return null;
  const typeAttr = (el.getAttribute("type") || "").trim().toLowerCase();
  if (!typeAttr) return null;
  if (!/^[a-z-]+$/.test(typeAttr)) return null;
  return `${selector}[type="${escapeCssValue(typeAttr)}"]`;
}

function buildStableClassSelector(el: HTMLElement, tag: string): string | null {
  const tokens = getStableClassTokens(el);
  if (tokens.length === 0) return null;

  const escaped = tokens.map((token) => CSS.escape(token));

  for (const cls of escaped) {
    const base = `${tag}.${cls}`;
    const typed = withTypeQualifier(el, base);
    if (typed && querySelectorCount(typed) === 1) return typed;
    if (querySelectorCount(base) === 1) return base;
  }

  for (let i = 0; i < escaped.length; i++) {
    for (let j = i + 1; j < escaped.length; j++) {
      const pair = `${tag}.${escaped[i]}.${escaped[j]}`;
      const typed = withTypeQualifier(el, pair);
      if (typed && querySelectorCount(typed) === 1) return typed;
      if (querySelectorCount(pair) === 1) return pair;
    }
  }

  const best = `${tag}.${escaped[0]}`;
  const bestTyped = withTypeQualifier(el, best);
  if (bestTyped && querySelectorCount(bestTyped) > 0 && querySelectorCount(bestTyped) <= 3) return bestTyped;
  if (querySelectorCount(best) > 0 && querySelectorCount(best) <= 3) return best;
  return null;
}

export function computeSelectorScore(type: string, el: HTMLElement): number {
  switch (type) {
    case "css": {
      const role = el.getAttribute("role");
      const ariaLabel = el.getAttribute("aria-label");
      const tag = el.tagName.toLowerCase();
      // Combined role+aria-label on a non-native-role element is the most precise
      const nativeRole = (tag === "button" && role === "button") || (tag === "a" && role === "link");
      if (role && ariaLabel && !nativeRole) return 0.92;
      for (const attr of ["data-testid", "data-qa", "data-cy", "data-test"]) {
        if (el.hasAttribute(attr)) return 0.95;
      }
      if (ariaLabel) return 0.85;
      if (el.id && !isGeneratedId(el.id)) return 0.80;
      if (el.getAttribute("name")) return 0.75;
      if (role) return 0.65;
      if (getStableClassTokens(el).length > 0) return 0.62;
      const sibs = countSameTagSiblings(el);
      if (sibs > 1) return 0.30;
      return 0.50;
    }
    case "text":
      return 0.70;
    case "accessibility": {
      const role = el.getAttribute("role");
      const label = el.getAttribute("aria-label");
      if (role && label) return 0.85;
      if (role) return 0.65;
      return 0.50;
    }
    case "xpath":
      return 0.20;
    default:
      return 0.10;
  }
}

const LANDMARK_TAGS = new Set(["main", "nav", "header", "footer", "aside", "section", "article", "dialog", "form"]);
const LANDMARK_ROLES = new Set([
  "main", "navigation", "banner", "contentinfo", "complementary", "region",
  "search", "dialog", "alertdialog", "form",
]);

export function buildLandmarkPath(el: HTMLElement, maxDepth = 8): string | null {
  const parts: string[] = [];
  let current = el.parentElement;
  let depth = 0;

  while (current && current !== document.body && current !== document.documentElement && depth < maxDepth) {
    const tag = current.tagName.toLowerCase();
    const role = (current.getAttribute("role") || "").toLowerCase();
    const label = (current.getAttribute("aria-label") || current.getAttribute("title") || "").trim();

    if (LANDMARK_TAGS.has(tag) || LANDMARK_ROLES.has(role)) {
      const name = role || tag;
      parts.unshift(label ? `${name}[${label.slice(0, 40)}]` : name);
    }
    current = current.parentElement;
    depth++;
  }

  return parts.length > 0 ? parts.join(" > ") : null;
}

function countSameTagSiblings(el: HTMLElement): number {
  const parentEl = el.parentElement;
  if (!parentEl) return 0;
  const tag = el.tagName.toLowerCase();
  const children = Array.from(parentEl.children) as HTMLElement[];
  return children.filter((s) => s.tagName.toLowerCase() === tag).length;
}

function siblingIndex(el: HTMLElement): number {
  const parentEl = el.parentElement;
  if (!parentEl) return 1;
  const tag = el.tagName.toLowerCase();
  const siblings = Array.from(parentEl.children) as HTMLElement[];
  const filtered = siblings.filter((s) => s.tagName.toLowerCase() === tag);
  return filtered.indexOf(el) + 1;
}

export function buildCssSelector(el: HTMLElement): string {
  const tag = el.tagName.toLowerCase();
  const role = el.getAttribute("role");
  const ariaLabel = el.getAttribute("aria-label");

  // 1. Combined role+aria-label — survives framework rebuilds; most specific
  //    Skip combining when role is redundant for the native element (button, a)
  if (role && ariaLabel) {
    const nativeRole = (tag === "button" && role === "button") || (tag === "a" && role === "link");
    if (!nativeRole) {
      return `[role="${escapeCssValue(role)}"][aria-label="${escapeCssValue(ariaLabel)}"]`;
    }
  }

  // 2. Developer-placed automation attributes (highest confidence)
  for (const attr of ["data-testid", "data-qa", "data-cy", "data-test"]) {
    const val = el.getAttribute(attr);
    if (val) return `${tag}[${attr}="${escapeCssValue(val)}"]`;
  }

  // 3. aria-label alone (more stable than IDs in SPAs)
  if (ariaLabel) return `${tag}[aria-label="${escapeCssValue(ariaLabel)}"]`;

  // 4. Non-generated ID
  if (el.id && !isGeneratedId(el.id)) return `#${CSS.escape(el.id)}`;

  // 5. name attribute (form controls)
  const name = el.getAttribute("name");
  if (name) return `${tag}[name="${escapeCssValue(name)}"]`;

  // 6. role alone (weaker — many elements share the same role)
  if (role) return `${tag}[role="${escapeCssValue(role)}"]`;

  // 7. Stable class-based selector (e.g. LinkedIn msg-form__send-button)
  const stableClassSelector = buildStableClassSelector(el, tag);
  if (stableClassSelector) return stableClassSelector;

  // 8. Structural path fallback
  const parts: string[] = [];
  let current: HTMLElement | null = el;
  while (current && current !== document.body && current !== document.documentElement) {
    let segment = current.tagName.toLowerCase();
    const sibs = countSameTagSiblings(current);
    if (sibs > 1) {
      segment += `:nth-of-type(${siblingIndex(current)})`;
    }
    parts.unshift(segment);
    current = current.parentElement;
  }
  return parts.join(" > ");
}

export function buildTextSelector(el: HTMLElement): string | null {
  const TEXT_TAGS = new Set([
    "a", "button", "h1", "h2", "h3", "h4", "h5", "h6",
    "label", "span", "li", "td", "th", "p", "div",
  ]);
  if (!TEXT_TAGS.has(el.tagName.toLowerCase())) return null;

  const text = el.textContent || "";
  const trimmed = text.trim();
  if (!trimmed || trimmed.length === 0) return null;

  // When the clicked element wraps a lot of nested content (e.g., LinkedIn
  // conversation card with name + timestamp + status + preview), the raw
  // textContent is too noisy to match at replay time. Look for a short
  // distinctive descendant (heading, aria-label) and use that instead.
  if (trimmed.length > 200) {
    const headings = el.querySelectorAll<HTMLElement>("h1,h2,h3,h4,h5,h6");
    for (const h of headings) {
      const ht = (h.textContent || "").trim();
      if (ht && ht.length <= 120) return ht.replace(/\s+/g, " ");
    }
    // Fallback: any element with aria-label of reasonable length
    const labelled = el.querySelector<HTMLElement>("[aria-label]");
    if (labelled) {
      const lt = (labelled.getAttribute("aria-label") || "").trim();
      if (lt && lt.length <= 120) return lt.replace(/\s+/g, " ");
    }
    return null;
  }

  return trimmed.replace(/\s+/g, " ");
}

export function buildAccessibilitySelector(el: HTMLElement): string | null {
  const role = el.getAttribute("role");
  const label = el.getAttribute("aria-label");
  if (!role && !label) return null;
  return JSON.stringify([role || "", label || ""]);
}

export function buildXPathSelector(el: HTMLElement): string {
  const parts: string[] = [];
  let current: HTMLElement | null = el;

  while (current && current !== document.documentElement) {
    const tag = current.tagName.toLowerCase();
    const pEl: HTMLElement | null = current.parentElement;
    if (pEl) {
      const children = Array.from(pEl.children) as HTMLElement[];
      const sameTagSiblings = children.filter((s) => s.tagName.toLowerCase() === tag);
      if (sameTagSiblings.length > 1) {
        const index = sameTagSiblings.indexOf(current) + 1;
        parts.unshift(`${tag}[${index}]`);
      } else {
        parts.unshift(tag);
      }
    } else {
      parts.unshift(tag);
    }
    current = pEl;
  }
  parts.unshift("html");
  return "/" + parts.join("/");
}

export interface PatternInfo {
  parentSelector: string;
  siblingTag: string;
  siblingCount: number;
  childIndex: number;
  structureHash: string;
}

export function detectPattern(el: Element): PatternInfo | null {
  if (!(el instanceof HTMLElement)) return null;
  const parent = el.parentElement;
  if (!parent) return null;

  const tag = el.tagName.toLowerCase();
  const siblings = Array.from(parent.children).filter(
    (c) => c.tagName.toLowerCase() === tag,
  );

  if (siblings.length < 3) return null;

  const index = siblings.indexOf(el);
  if (index === -1) return null;

  const parentSelector = parent.id
    ? `#${parent.id}`
    : parent.className
      ? `.${parent.className.split(" ")[0]}`
      : parent.tagName.toLowerCase();

  return {
    parentSelector: `${parentSelector} > ${tag}`,
    siblingTag: tag,
    siblingCount: siblings.length,
    childIndex: index,
    structureHash: `${tag}-${siblings.length}-${tag}`,
  };
}

const ANCHOR_RELATIONS = ["below", "above", "left", "right", "inside"] as const;
type AnchorRelation = typeof ANCHOR_RELATIONS[number];

export function buildAnchorSelector(el: HTMLElement): SelectorSet | null {
  const parent = el.parentElement;
  if (!parent) return null;

  const anchorEl = findNearestStableAncestor(el);
  if (!anchorEl) return null;

  const anchorSelector = buildCssSelector(anchorEl);
  if (!anchorSelector) return null;

  const elRect = el.getBoundingClientRect();
  const anchorRect = anchorEl.getBoundingClientRect();

  let relation: AnchorRelation = "inside";
  const dy = elRect.top - anchorRect.bottom;
  const dx = elRect.left - anchorRect.right;

  if (dy > 0) relation = "below";
  else if (Math.abs(dy) < anchorRect.height && dx > 0) relation = "right";
  else if (Math.abs(dy) < anchorRect.height && dx < -elRect.width) relation = "left";
  else if (-dy > elRect.height) relation = "above";

  const value = JSON.stringify({
    anchor_selector: anchorSelector,
    relation,
    offset_x: Math.round(elRect.left - anchorRect.left),
    offset_y: Math.round(elRect.top - anchorRect.top),
  });

  return { type: "anchor", value, score: 0.55 };
}

function findNearestStableAncestor(el: HTMLElement): HTMLElement | null {
  let current: HTMLElement | null = el.parentElement;
  let depth = 0;
  while (current && current !== document.body && current !== document.documentElement && depth < 5) {
    if (current.id || current.getAttribute("data-testid") || current.getAttribute("role")) {
      return current;
    }
    current = current.parentElement;
    depth++;
  }
  return null;
}

// Walks up from a shadow-DOM-internal element collecting the shadow host
// chain. Returns null when the element is NOT inside a shadow root.
//
// shadow_css selector value is JSON of the form
//   { host_chain: ["div[data-testid='interop-shadowdom']", ...], target: "button[aria-label='Send']" }
// Replay piercing logic walks host_chain through shadowRoot.querySelector at
// each step, then queries the target in the final shadow root.
export function buildShadowCssSelector(el: HTMLElement): SelectorSet | null {
  const root = el.getRootNode();
  if (!(root instanceof ShadowRoot)) return null;

  const targetSelector = buildCssSelector(el);
  if (!targetSelector) return null;

  const hostChain: string[] = [];
  let currentRoot: ShadowRoot | null = root;
  while (currentRoot) {
    const host: Element = currentRoot.host;
    if (!(host instanceof HTMLElement)) break;
    hostChain.unshift(buildCssSelector(host));
    const parent: Node = host.getRootNode();
    currentRoot = parent instanceof ShadowRoot ? parent : null;
  }

  if (hostChain.length === 0) return null;

  return {
    type: "shadow_css",
    value: JSON.stringify({ host_chain: hostChain, target: targetSelector }),
    // Higher than plain css (0.85) because it pierces shadow DOM unambiguously.
    score: 0.97,
  };
}

export function buildSelectors(el: HTMLElement): SelectorSet[] {
  const chain: SelectorSet[] = [];

  const shadowCss = buildShadowCssSelector(el);
  if (shadowCss) chain.push(shadowCss);

  const a11y = buildAccessibilitySelector(el);
  if (a11y) chain.push({ type: "accessibility", value: a11y, score: computeSelectorScore("accessibility", el) });

  const css = buildCssSelector(el);
  if (css) chain.push({ type: "css", value: css, score: computeSelectorScore("css", el) });

  const text = buildTextSelector(el);
  if (text) chain.push({ type: "text", value: text, score: computeSelectorScore("text", el) });

  const xpath = buildXPathSelector(el);
  chain.push({ type: "xpath", value: xpath, score: computeSelectorScore("xpath", el) });

  const anchor = buildAnchorSelector(el);
  if (anchor) chain.push(anchor);

  chain.sort((a, b) => (b.score || 0) - (a.score || 0));
  return chain;
}
